networks:
  jenkins-net:
    driver: bridge
    name: jenkins-net

volumes:
  jenkins_data:
  jenkins_workspace:

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./workspace:/workspace
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.TcpSlaveAgentListener.hostName=0.0.0.0
    networks:
      - jenkins-net
